import Head from "next/head";
import Header from "../components/Header";
import XOGame from "../components/XOGame";
import Main from "../components/Home";


export default function Home() {
  return (
    <>
      <Head>
        <title>X O Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap');
        </style> 
      </Head>
      
      <Main>
        <Header />
        <XOGame />
        
      </Main>
    </>
  )
}
