import styled from "styled-components";
import Head from "next/head";
import Header from "../components/Header";
import Link from "next/link";
import Image from "next/image";
import XOPic from "../components/pictures/XOPic.png";
import Memory from "../components/pictures/Memory.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Minigame Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" type="image/x-icon" href="./favicon.ico" />
      </Head>
      <Header />
      <Container>
        <Link href="/xogame"><StyledLink><Image alt="" width="290" height="290
        " src={XOPic} />X and O Game</StyledLink></Link>
        <Link href="/memory"><StyledLink><Image alt="" width="290" height="290
        " src={Memory} />Memory</StyledLink></Link>
      </Container>
    </>
  )
}

const Container = styled.main`
  display: flex;
  justify-content: center;
  flex-direction: column;
`;

const StyledLink = styled.a`
  display: grid;
  place-items: center;
  background: whitesmoke;
  color: black;
  box-shadow: 3px 3px 20px 0px rgba(245,245,245,0.4);
  border-radius: 15px;
  margin: 22px;
  padding: 5px;
  width: 330px;
  height: 350px;
  font-size: 1.5rem;
`;
